'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number(v||0).toLocaleString('vi-VN',{maximumFractionDigits:3});
const day=v=>v?new Date(v).toLocaleDateString('vi-VN'):'—';
const time=v=>v?new Date(v).toLocaleString('vi-VN'):'—';
const today=()=>new Date().toLocaleDateString('en-CA');
const state={user:null,view:'dashboard',items:[],categories:[],locations:[],cart:[],importRows:[],stockRows:[],page:1,filters:{},labels:[],events:null};
const views=[['dashboard','Tổng quan'],['inventory','Tồn kho khả dụng'],['import','Nhập kho & In tem'],['export','Xuất kho'],['transfer','Xuất cho khoa khác'],['transactions','Phiếu giao dịch'],['stocktake','Kiểm kê định kỳ'],['report','Báo cáo nhập xuất tồn'],['items','Danh mục mặt hàng'],['locations','Vị trí lưu kho'],['admin','Tài khoản & Quyền hạn'],['audit','Nhật ký hoạt động'],['config','Thiết lập & Sao lưu']];
const manager=()=>['ADMIN','MANAGER'].includes(state.user?.role);
const can=p=>state.user?.role==='ADMIN'||state.user?.permissions?.[p]===true;
const title=v=>views.find(x=>x[0]===v)?.[1]||v;
const table=(headers,rows)=>`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.join(''):`<tr><td colspan="${headers.length}" class="empty">Chưa có dữ liệu phù hợp.</td></tr>`}</tbody></table></div>`;
const td=v=>`<td>${esc(v)}</td>`;
const button=(label,action,id='',klass='')=>`<button type="button" data-action="${action}" data-id="${esc(id)}" class="${klass}">${esc(label)}</button>`;
const options=(rows,value='',placeholder='Tất cả')=>`<option value="">${placeholder}</option>`+rows.map(x=>`<option value="${x.id}" ${String(value)===String(x.id)?'selected':''}>${esc(x.name||x.full_name||x.code)}</option>`).join('');
const field=(label,name,value='',type='text',attrs='')=>`<label>${esc(label)}<input name="${name}" type="${type}" value="${esc(value)}" ${attrs}></label>`;
function notice(message,bad=false){$('#notice').hidden=false;$('#notice').className=bad?'bad':'';$('#notice').textContent=message;}
function error(err){notice(err.message||String(err),true);}
function modal(html){$('#modal-content').innerHTML=html;$('#modal').showModal();}
function closeModal(){$('#modal').close();}
function query(obj){return new URLSearchParams(Object.entries(obj).filter(([,v])=>v!==''&&v!=null)).toString();}
function filterDates(includeType=true){const f=state.filters[state.view]||{};return `<form data-form="filters" class="toolbar">${field('Từ ngày','from_date',f.from_date||'','date')}${field('Đến ngày','to_date',f.to_date||'','date')}${includeType?`<label>Loại phiếu<select name="type"><option value="ALL">Nhập & Xuất</option><option value="IMPORT" ${f.type==='IMPORT'?'selected':''}>Phiếu nhập</option><option value="EXPORT" ${f.type==='EXPORT'?'selected':''}>Phiếu xuất</option></select></label>`:''}${button('Lọc','submit-filter')}${button('Xóa lọc','reset-filter')}</form>`;}
function pager(data){return `<div class="pager"><span>${data.total} bản ghi · Trang ${state.page}</span>${button('←','page',state.page-1)}${button('→','page',state.page*50<data.total?state.page+1:state.page)}</div>`;}
async function catalogs(){const [a,b]=await Promise.all([api.request('/items'),api.getLocations()]);state.items=a.items;state.categories=a.categories;state.locations=b.locations;}
function nav(){const allowed=views.filter(([v])=>!(v==='admin'&&state.user.role!=='ADMIN')&&!(['audit','stocktake'].includes(v)&&!manager())&&!(v==='import'&&!can('can_import'))&&!(['export','transfer'].includes(v)&&!can('can_export')));const icons={dashboard:'▦',inventory:'▣',import:'⇩',export:'⇧',transfer:'⇄',transactions:'▤',stocktake:'☑',report:'△',items:'⊞',locations:'▥',admin:'♙',audit:'◷',config:'⚙'};$('#navigation').innerHTML=allowed.map(([v,n])=>`${v==='dashboard'?'<p class="nav-label">NGHIỆP VỤ KHO</p>':v==='items'?'<p class="nav-label">HỆ THỐNG DANH MỤC</p>':v==='admin'?'<p class="nav-label">QUẢN TRỊ</p>':''}<button data-action="nav" data-id="${v}" class="${v===state.view?'active':''}"><span class="nav-icon" aria-hidden="true">${icons[v]}</span>${esc(n)}</button>`).join('');$('#quick-actions').innerHTML=button('▥ Quét mã [F2]','nav','export')+(can('can_import')?button('⇩ Tạo phiếu nhập [F3]','nav','import'):'')+(can('can_export')?button('⇧ Tạo phiếu xuất [F4]','nav','export','primary'):'');$('#server-address').textContent='● Máy chủ: '+new URL(api.baseUrl).host;}
async function show(view,keep=false){state.view=view;if(!keep)state.page=1;nav();$('#page-title').textContent=title(view);$('#breadcrumb').textContent=title(view).toUpperCase();$('#content').innerHTML='<div class="loading">Đang tải dữ liệu…</div>';try{await renders[view]();$('#sync-status').textContent='Đồng bộ lúc '+new Date().toLocaleTimeString('vi-VN');}catch(err){$('#content').innerHTML='<div class="panel empty">Không thể tải dữ liệu. Kiểm tra kết nối rồi bấm Làm mới.</div>';error(err);}}
async function session(){const r=await api.request('/auth/me');state.user=r.user;if(typeof state.user.permissions==='string')state.user.permissions=JSON.parse(state.user.permissions);$('#identity').textContent=`${state.user.full_name} · ${state.user.role}`;$('#login-screen').hidden=true;$('#workspace').hidden=false;await catalogs();await show('dashboard');connectEvents();}
function logout(){api.setToken(null);state.events?.abort();state.user=null;state.cart=[];state.importRows=[];state.stockRows=[];$('#workspace').hidden=true;$('#login-screen').hidden=false;closeModal();}
async function connectEvents(){state.events?.abort();if(!state.user)return;const controller=new AbortController();state.events=controller;
 try{const r=await fetch(api.baseUrl+'/events',{headers:{Authorization:`Bearer ${api.token}`},signal:controller.signal});if(!r.ok){if(r.status===401){logout();return;}throw Error();}
 $('#connection-status').textContent='Trực tuyến';$('#connection-status').className='badge';const reader=r.body.getReader(),decoder=new TextDecoder();let pending='',first=true;
 while(true){const {value,done}=await reader.read();if(done)break;pending+=decoder.decode(value,{stream:true});let at;
 while((at=pending.indexOf('\n\n'))>=0){const frame=pending.slice(0,at);pending=pending.slice(at+2);if(frame.startsWith('event: expired')){logout();return;}if(frame.startsWith('event: unavailable')){$('#connection-status').textContent='Đang nối lại';$('#connection-status').className='badge warn';}
 if(frame.startsWith('event: change')){$('#sync-status').textContent='Cập nhật trực tiếp '+new Date().toLocaleTimeString('vi-VN');if(!first&&['dashboard','inventory','transactions','audit'].includes(state.view)&&!$('#modal').open)await show(state.view,true);first=false;}}
 }
 }catch(e){if(controller.signal.aborted)return;}if(state.user&&!controller.signal.aborted){$('#connection-status').textContent='Đang nối lại';$('#connection-status').className='badge warn';setTimeout(()=>{if(state.events===controller)connectEvents();},3000);}}
const renders={};
renders.dashboard=async()=>{
 const [a,b,c]=await Promise.all([api.getDashboardStats(),api.getInventory({include_zero:'true'}),api.request('/tickets')]);const s=a.stats;
 const low=state.items.map(i=>({...i,total:b.inventory.filter(x=>x.item_code===i.code).reduce((n,x)=>n+Number(x.current_quantity),0)})).filter(i=>i.total<Number(i.min_stock));
 const exp=b.inventory.filter(x=>(x.is_expired||x.is_near_expire)&&Number(x.current_quantity)>0);
 const cards=exp.slice(0,12).map(x=>`<article class="alert-card ${x.is_expired?'bad':'near'}"><div class="alert-heading"><strong>${esc(x.item_code)} ${esc(x.item_name)}</strong><span class="badge ${x.is_expired?'bad':'info'}">${x.is_expired?'ĐÃ HẾT HẠN':`SẮP HẾT HẠN (${x.days_remaining} NGÀY)`}</span></div><p>Lô: <b>${esc(x.batch_code)}</b> &nbsp; Hạn dùng: <b>${day(x.expiry_date)}</b> &nbsp; Vị trí: ${esc(x.location_name||'Chưa gán')}</p><div class="alert-bottom"><span>Số lượng: <b>${num(x.current_quantity)}</b> ${esc(x.unit)}</span>${button('Kiểm tra lô','batch',x.batch_code)}</div></article>`).join('')+low.map(i=>`<article class="alert-card"><div class="alert-heading"><strong>${esc(i.code)} ${esc(i.name)}</strong><span class="badge warn">TỒN DƯỚI NGƯỠNG</span></div><div class="alert-bottom"><p>Tồn hiện tại: <b>${num(i.total)}</b> ${esc(i.unit)} &nbsp; Mức an toàn: <b>${num(i.min_stock)}</b> ${esc(i.unit)}</p>${can('can_import')?button('Tạo phiếu nhập','nav','import','primary'):''}</div></article>`).join('');
 $('#content').innerHTML=`<div class="stats">${[['Mặt hàng đang quản lý',s.total_items,'mặt hàng','Danh mục thuốc, hóa chất & vật tư'],['Cảnh báo tồn thấp',s.low_stock_count,'mặt hàng','Cần bổ sung tồn kho'],['Sắp hết hạn',s.near_expire_count,'đầu mục','Ưu tiên kiểm tra và cấp phát'],['Đầu mục đã hết hạn',s.expired_count,'đầu mục','Kiểm tra các lô hết hạn']].map(([k,v,u,n],i)=>`<div class="stat stat-${i}"><span>${k}</span><div><strong>${num(v)}</strong> ${u}</div><p>${n}</p></div>`).join('')}</div><div class="grid2 dashboard-grid"><section class="panel"><div class="section-heading"><div><h2>Cảnh báo tồn kho & hạn dùng cần xử lý</h2><p class="muted">Theo dõi ngưỡng an toàn & phân lô khả dụng</p></div><span class="badge">${exp.length+low.length} cảnh báo</span></div>${cards||'<div class="empty">Không có cảnh báo cần xử lý.</div>'}</section><section class="panel flush"><div class="panel-title"><div><h2>Phiếu giao dịch gần đây</h2><p class="muted">Chứng từ nhập - xuất kho</p></div>${button('Tất cả →','nav','transactions')}</div>${table(['Số phiếu','Loại','Thời điểm','Người lập',''],c.tickets.slice(0,8).map(t=>`<tr><td><strong>${esc(t.ticket_code)}</strong></td><td><span class="badge ${t.type==='IMPORT'?'':'info'}">${t.type==='IMPORT'?'Nhập kho':'Xuất kho'}</span></td>${td(time(t.created_at))}${td(t.creator_name)}<td>${button('↗','ticket',t.type+'/'+t.id)}</td></tr>`))}</section></div><details class="panel"><summary>Nhật ký hoạt động gần đây</summary>${table(['Thời gian','Tài khoản','Thao tác'],s.recent_logs.map(l=>`<tr>${td(time(l.created_at))}${td(l.full_name)}${td(l.action)}</tr>`))}</details>`;
};
renders.inventory=async()=>{const f=state.filters.inventory||{},r=await api.getInventory(f);$('#content').innerHTML=`<form data-form="filters" class="toolbar"><label>Tìm mã lô / tên hàng<input name="search" value="${esc(f.search)}"></label><label>Vị trí<select name="location_id">${options(state.locations,f.location_id)}</select></label><label>Hạn dùng<select name="status"><option value="">Tất cả</option>${[['NEAR','Sắp hết hạn'],['EXPIRED','Đã hết hạn'],['ACTIVE','Còn hạn']].map(([k,v])=>`<option value="${k}" ${f.status===k?'selected':''}>${v}</option>`).join('')}</select></label><label class="checklabel"><input type="checkbox" name="include_zero" value="true" ${f.include_zero==='true'?'checked':''}>Gồm lô hết tồn</label><button type="submit">Lọc</button>${button('Xóa lọc','reset-filter')}</form><form data-form="inventory-scan" class="toolbar panel scanner"><label>Tra cứu Code 128<input name="code" required placeholder="Quét mã rồi Enter"></label><button type="submit">Tra cứu lô</button></form><div class="panel flush">${table(['Mã lô','Mặt hàng','Hạn dùng','Vị trí','Tồn','Trạng thái',''],r.inventory.map(x=>`<tr><td><code>${esc(x.batch_code)}</code></td>${td(x.item_name)}${td(day(x.expiry_date))}${td(x.location_name||'Chưa gán')}<td class="numeric">${num(x.current_quantity)} ${esc(x.unit)}</td><td><span class="badge ${x.is_expired?'bad':x.is_near_expire?'warn':''}">${x.is_expired?'Hết hạn':x.is_near_expire?'Sắp hết hạn':'Còn hạn'}</span></td><td>${button('Chi tiết','batch',x.batch_code)}</td></tr>`))}</div>`;};
function importRow(i){return `<tr><td><select name="item_id" required>${options(state.items,i.item_id,'Chọn mặt hàng')}</select></td><td><input name="batch_code" value="${esc(i.batch_code)}" placeholder="Tự sinh" maxlength="50" pattern="[A-Za-z0-9._-]+"></td><td><input name="quantity" type="number" min="0.001" step="0.001" value="${i.quantity||1}" required></td><td><input name="unit_price" type="number" min="0" step="0.01" value="${i.unit_price||0}" required></td><td><input name="expiry_date" type="date" value="${esc(i.expiry_date)}" required></td><td><input name="label_print_count" type="number" min="1" max="200" value="${i.label_print_count||1}" required></td><td>${button('×','remove-row')}</td></tr>`;}
renders.import=async()=>{$('#content').innerHTML=`<form data-form="import"><div class="panel"><h3>Thông tin phiếu nhập</h3><div class="form-grid">${field('Nhà cung cấp','supplier_name','','text','required maxlength="150"')}<label>Vị trí lưu kho<select name="location_id" required>${options(state.locations,'','Chọn vị trí')}</select></label>${field('Ghi chú','notes')}</div><h3>Mặt hàng nhập theo lô</h3><div class="table-wrap"><table><thead><tr>${['Mặt hàng','Mã lô','Số lượng','Giá nhập','Hạn dùng','Số tem',''].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody id="import-rows">${importRow({})}</tbody></table></div><br>${button('＋ Thêm dòng','add-import')}</div><div class="actionbar"><span>Lưu thành công trước khi in. Có thể in lại từ lịch sử phiếu.</span><button class="primary" type="submit">Lưu phiếu nhập [F9]</button></div></form><div id="label-result"></div>`;};
function cartHTML(){return table(['Mã lô','Mặt hàng','Hạn dùng','Tồn','Số lượng xuất',''],state.cart.map((x,i)=>`<tr>${td(x.batch_code)}${td(x.item_name)}${td(day(x.expiry_date))}<td class="numeric">${num(x.current_quantity)}</td><td><input data-cart="${i}" type="number" min="0.001" max="${x.current_quantity}" step="0.001" value="${x.quantity}" aria-label="Số lượng xuất"></td><td>${button('Bỏ','remove-cart',i)}</td></tr>`));}
renders.export=async()=>{$('#content').innerHTML=`<form data-form="export-scan" class="panel scanner toolbar"><label>Quét mã lô Code 128<input name="code" required autofocus placeholder="Đặt con trỏ tại đây và quét mã"></label><button type="submit" class="primary">Thêm lô [Enter]</button></form><div class="panel flush" id="cart">${cartHTML()}</div><form data-form="export"><div class="panel form-grid">${field(state.view==='transfer'?'Khoa tiếp nhận':'Đơn vị nhận','department_name','','text','required maxlength="150"')}${field('Lý do / ghi chú','notes','','text','required')}</div><div class="actionbar"><span>Bước 1/2 · Kiểm tra danh sách và số lượng</span><div class="actions">${button('Làm lại','clear-cart')}<button class="primary" type="submit">Kiểm tra & Xác nhận →</button></div></div></form>`;};renders.transfer=renders.export;
renders.transactions=async()=>{const r=await api.request('/tickets?'+query({...state.filters.transactions,page:state.page}));$('#content').innerHTML=filterDates()+`<div class="panel flush">${table(['Phiếu','Loại','Đối tác / Khoa','Người lập','Thời gian','Trạng thái',''],r.tickets.map(t=>`<tr><td><code>${esc(t.ticket_code)}</code></td>${td(t.type==='IMPORT'?'Nhập':'Xuất')}${td(t.partner)}${td(t.creator_name)}${td(time(t.created_at))}<td><span class="badge ${t.status==='CANCELLED'?'bad':''}">${t.status==='CANCELLED'?'Đã hủy':'Đã ghi sổ'}</span></td><td>${button('Chi tiết','ticket',t.type+'/'+t.id)}</td></tr>`))}${pager(r)}</div>`;};
renders.report=async()=>{const f=state.filters.report||{},mode=f.mode||'inventory',url=mode==='inventory'?'/reports/inventory':'/reports/movements';const r=await api.request(url+'?'+query(f));state.reportEndpoint=url+'?'+query(f);$('#content').innerHTML=`<div class="print-heading"><h2>BỆNH VIỆN 198 — KHOA VI SINH</h2><h3>${mode==='inventory'?'Báo cáo nhập xuất tồn':'Báo cáo giao dịch nhập / xuất'}</h3><p>${esc(f.from_date||'Tất cả')} — ${esc(f.to_date||'Hiện tại')}</p></div>`+filterDates()+`<div class="toolbar"><label>Dạng báo cáo<select id="report-mode"><option value="inventory">Nhập – Xuất – Tồn theo lô</option><option value="movements" ${mode==='movements'?'selected':''}>Chi tiết phiếu nhập / xuất</option></select></label>${button('Xuất Excel','excel','','primary')}${button('In A4','print')}</div><div class="panel flush">${mode==='inventory'?table(['Lô','Mặt hàng','ĐVT','Tồn đầu','Nhập','Xuất','Điều chỉnh / hoàn','Tồn cuối'],r.data.map(x=>`<tr>${td(x.batch_code)}${td(x.item_name)}${td(x.unit)}${['opening_quantity','import_quantity','export_quantity','adjustment_quantity','closing_quantity'].map(k=>`<td class="numeric">${num(x[k])}</td>`).join('')}</tr>`)):table(['Phiếu','Loại','Ngày','Người lập','Mặt hàng','Lô','Số lượng','Trạng thái'],r.data.map(x=>`<tr>${td(x.ticket_code)}${td(x.type==='IMPORT'?'Nhập':'Xuất')}${td(time(x.created_at))}${td(x.creator_name)}${td(x.item_name)}${td(x.batch_code)}<td class="numeric">${num(x.quantity)} ${esc(x.unit)}</td>${td(x.status==='CANCELLED'?'Đã hủy':'Đã ghi sổ')}</tr>`))}</div><p class="muted">Phiếu xuất đã hủy vẫn xuất hiện trong lịch sử. Báo cáo tồn ghi nhận phần hoàn trả vào thời điểm hủy.</p>`;};
renders.stocktake=async()=>{const r=await api.getStocktakes();$('#content').innerHTML=`<form data-form="start-stocktake" class="panel toolbar"><label>Vị trí kiểm kê<select name="location_id" required>${options(state.locations,'','Chọn vị trí')}</select></label><button class="primary" type="submit">Lập phiếu kiểm kê</button></form><div class="panel flush">${table(['Phiếu','Vị trí','Ngày lập','Người lập','Trạng thái',''],r.stocktakes.map(t=>`<tr>${td(t.ticket_code)}${td(t.location_name)}${td(time(t.created_at))}${td(t.creator_name)}${td(t.status==='ADJUSTED'?'Đã điều chỉnh':'Chờ đối soát')}<td>${button('Đối soát','stock-detail',t.id)}</td></tr>`))}</div>`;};
renders.items=async()=>{await catalogs();$('#content').innerHTML=`<div class="toolbar">${manager()?button('＋ Mặt hàng','edit-item','','primary')+button('＋ Nhóm danh mục','category'):''}</div><div class="panel flush">${table(['Mã','Tên mặt hàng','Nhóm','ĐVT','Ngưỡng tồn','Ngưỡng hạn (ngày)',''],state.items.map(i=>`<tr>${td(i.code)}${td(i.name)}${td(i.category_name)}${td(i.unit)}<td class="numeric">${num(i.min_stock)}</td>${td(i.expire_alert_days??'Theo hệ thống')}<td>${manager()?button('Sửa','edit-item',i.id):''}</td></tr>`))}</div>`;};
renders.locations=async()=>{await catalogs();$('#content').innerHTML=`<div class="toolbar">${manager()?button('＋ Vị trí','location','','primary'):''}</div><div class="panel flush">${table(['Mã','Vị trí','Nhiệt độ','Mô tả'],state.locations.map(l=>`<tr>${td(l.code)}${td(l.name)}${td(l.temp_range)}${td(l.description)}</tr>`))}</div>`;};
renders.admin=async()=>{const r=await api.getUsers();state.users=r.users;$('#content').innerHTML=`<div class="toolbar">${button('＋ Cấp tài khoản','edit-user','','primary')}</div><div class="panel flush">${table(['Tên đăng nhập','Họ tên','Vai trò','Quyền','Trạng thái',''],r.users.map(u=>{const p=typeof u.permissions==='string'?JSON.parse(u.permissions):u.permissions||{};return `<tr>${td(u.username)}${td(u.full_name)}${td(u.role)}${td(u.role==='ADMIN'?'Toàn quyền':[p.can_import?'Nhập':'',p.can_export?'Xuất':''].filter(Boolean).join(', '))}<td><span class="badge ${u.status==='LOCKED'?'bad':''}">${u.status==='LOCKED'?'Đã khóa':'Hoạt động'}</span></td><td class="actions">${button('Sửa quyền / Khóa','edit-user',u.id)}${u.id!==state.user.id?button('Xóa','delete-user',u.id,'danger'):''}</td></tr>`;}))}</div><p class="muted">Xóa tài khoản ngừng quyền sử dụng; tên người lập trong lịch sử được giữ để đối soát.</p>`;};
renders.audit=async()=>{const f=state.filters.audit||{},r=await api.request('/audit-logs?'+query({...f,page:state.page}));$('#content').innerHTML=filterDates(false)+`<form data-form="audit-filter" class="toolbar">${field('Mã tài khoản (tùy chọn)','user_id',f.user_id||'','number','min="1"')}${field('Thao tác chứa','action',f.action||'')}<button type="submit">Lọc hoạt động</button></form><div class="panel flush">${table(['Thời gian','Tài khoản','Thao tác','Đối tượng','Chi tiết'],r.logs.map(l=>`<tr>${td(time(l.created_at))}${td(l.full_name)}${td(l.action)}${td(l.target_type+' #'+l.target_id)}<td>${esc(typeof l.details==='string'?l.details:JSON.stringify(l.details))}</td></tr>`))}${pager(r)}</div>`;};
renders.config=async()=>{const r=await api.request('/configs'),c=Object.fromEntries(r.configs.map(x=>[x.config_key,x.config_value]));$('#content').innerHTML=`<div class="grid2"><div class="panel"><h3>Ngưỡng nghiệp vụ</h3>${[['DEFAULT_EXPIRE_ALERT_DAYS','Cảnh báo hạn dùng (ngày)',7,365],['CANCEL_EXPORT_LIMIT_HOURS','Thời hạn hủy phiếu (giờ)',24,168]].map(([key,label,value,max])=>`<form data-form="config" class="toolbar"><input type="hidden" name="config_key" value="${key}">${field(label,'config_value',c[key]||value,'number',`required min="1" max="${max}"`)}${state.user.role==='ADMIN'?'<button type="submit">Lưu</button>':''}</form>`).join('')}<p class="muted">Ngưỡng hạn hệ thống áp dụng cho mặt hàng không có ngưỡng riêng.</p></div><div class="panel"><h3>Sao lưu & Phục hồi</h3><p>Sao lưu chạy theo lịch trên máy chủ bằng dịch vụ visinh-backup.timer. Khôi phục cần tạm dừng ghi và do quản trị hạ tầng thực hiện.</p><br><p class="muted">Quy trình và lệnh khôi phục: docs/BACKUP_RESTORE.md. Không xóa dữ liệu nghiệp vụ khi hết hạn giữ bản sao lưu.</p></div></div>`;};
async function batchDetail(code){const {batch:b}=await api.scanBarcode(code);modal(`<h2>Thông tin lô ${esc(b.batch_code)}</h2><div class="form-grid"><p><strong>${esc(b.item_name)}</strong><br>${esc(b.item_code)}</p><p>Tồn: ${num(b.current_quantity)} ${esc(b.unit)}<br>HSD: ${day(b.expiry_date)}</p><p>${esc(b.location_name||'Chưa gán vị trí')}<br>Nhập: ${time(b.created_at)}</p><p>NCC: ${esc(b.supplier_name)}<br>Người nhập: ${esc(b.creator_name)}</p></div><img src="${esc(b.barcode_image)}" alt="Mã vạch lô" width="280">`);}
function labelHTML(labels){return labels.map(l=>`<div class="barcode-label"><strong>BV 198 · KHOA VI SINH</strong><p>${esc(l.item_name||'')}</p><img src="${esc(l.barcode_image)}" alt="Code 128"><p>${esc(l.batch_code)} · HSD ${day(l.expiry_date)}</p><p>${l.label_print_count||1} tem</p></div>`).join('');}
async function printLabels(){if(window.electronAPI){const r=await window.electronAPI.printBarcodeTicket(state.labels);if(!r.success)throw Error(r.error||'Chưa in được tem.');notice('Đã gửi lệnh in tem.');}else{modal(`<h2>In tem mã vạch</h2><div class="label-preview">${labelHTML(state.labels.flatMap(l=>Array.from({length:l.label_print_count||1},()=>({...l,label_print_count:1}))))}</div><div class="dialog-actions">${button('In','print','','primary')}</div>`);}}
async function ticketDetail(key){const {ticket:t}=await api.request('/tickets/'+key);modal(`<h2>${t.type==='IMPORT'?'Phiếu nhập':'Phiếu xuất'} ${esc(t.ticket_code)}</h2><p>${esc(t.supplier_name||t.department_name)} · ${time(t.created_at)} · ${esc(t.creator_name)}</p><p>${esc(t.notes||'')}</p><br>${table(['Mặt hàng','Mã lô','Hạn dùng','Số lượng','ĐVT'],t.items.map(i=>`<tr>${td(i.item_name)}${td(i.batch_code)}${td(day(i.expiry_date))}${td(num(i.quantity))}${td(i.unit)}</tr>`))}${t.status==='CANCELLED'?`<div class="review-list">Đã hủy · ${esc(t.cancel_reason)}<br>Phiếu đảo: ${esc(t.reversal_ticket_code)}</div>`:''}<div class="dialog-actions">${button('In phiếu A4','print')}${t.type==='IMPORT'?button('In lại tem','labels',t.id):t.status!=='CANCELLED'&&can('can_export')?button('Hủy & hoàn tồn','cancel-ticket',t.id,'danger'):''}</div>`);}
async function stockDetail(id){const r=await api.request('/stocktakes/'+id);modal(`<h2>Đối soát ${esc(r.ticket.ticket_code)}</h2>${table(['Lô','Mặt hàng','Số sổ','Thực đếm','Chênh lệch','Tồn hiện tại','Lý do'],r.items.map(i=>`<tr>${td(i.batch_code)}${td(i.item_name)}${td(num(i.book_quantity))}${td(num(i.actual_quantity))}${td(num(i.difference))}${td(num(i.current_quantity))}${td(i.reason)}</tr>`))}<div class="dialog-actions">${r.ticket.status==='DRAFT'?button('Xác nhận điều chỉnh tồn','adjust-stock',id,'primary'):''}</div>`);}
function userForm(id){const u=state.users?.find(x=>String(x.id)===id)||{},p=typeof u.permissions==='string'?JSON.parse(u.permissions):u.permissions||{};modal(`<h2>${id?'Cập nhật quyền / Khóa':'Cấp tài khoản'}</h2><form data-form="user" data-id="${esc(id)}"><div class="form-grid">${id?'':field('Tên đăng nhập','username','','text','required pattern="[A-Za-z0-9_.-]+" maxlength="50"')}${field('Họ và tên','full_name',u.full_name,'text','required maxlength="100"')}${id?'':field('Mật khẩu ban đầu','password','','password','required minlength="10" maxlength="72" autocomplete="new-password"')}<label>Vai trò<select name="role">${['STAFF','MANAGER','ADMIN'].map(v=>`<option ${u.role===v?'selected':''}>${v}</option>`).join('')}</select></label><label>Trạng thái<select name="status"><option value="ACTIVE">Hoạt động</option><option value="LOCKED" ${u.status==='LOCKED'?'selected':''}>Khóa</option></select></label></div><div class="toolbar"><label class="checklabel"><input type="checkbox" name="can_import" ${p.can_import?'checked':''}>Cho phép nhập kho</label><label class="checklabel"><input type="checkbox" name="can_export" ${p.can_export?'checked':''}>Cho phép xuất kho</label></div><button class="primary" type="submit">Lưu tài khoản</button></form>`);}
function itemForm(id){const i=state.items.find(x=>String(x.id)===id)||{};modal(`<h2>${id?'Cập nhật':'Thêm'} mặt hàng</h2><form data-form="item" data-id="${esc(id)}"><div class="form-grid">${field('Mã hàng','code',i.code,'text','required maxlength="50"')}${field('Tên mặt hàng','name',i.name,'text','required maxlength="200"')}<label>Nhóm<select name="category_id" required>${options(state.categories,i.category_id,'Chọn nhóm')}</select></label>${field('Đơn vị tính','unit',i.unit,'text','required maxlength="20"')}${field('Tồn tối thiểu','min_stock',i.min_stock??10,'number','required min="0" step="0.001"')}${field('Cảnh báo hạn (trống = hệ thống)','expire_alert_days',i.expire_alert_days??'','number','min="1" max="365"')}${field('Điều kiện bảo quản','storage_condition',i.storage_condition)}</div><button class="primary" type="submit">Lưu mặt hàng</button></form>`);}
const actions={
 nav:async id=>{closeModal();await show(id);},refresh:()=>show(state.view,true),logout,
 'submit-filter':()=>$('#content form[data-form="filters"]').requestSubmit(),
 'reset-filter':()=>{state.filters[state.view]={};return show(state.view);},
 page:id=>{state.page=Math.max(1,Number(id));return show(state.view,true);},
 batch:batchDetail,ticket:ticketDetail,'stock-detail':stockDetail,
 'add-import':()=>$('#import-rows').insertAdjacentHTML('beforeend',importRow({})),
 'remove-row':(_,el)=>{if($('#import-rows').children.length>1)el.closest('tr').remove();},
 'remove-cart':id=>{state.cart.splice(Number(id),1);$('#cart').innerHTML=cartHTML();},
 'clear-cart':()=>{state.cart=[];$('#cart').innerHTML=cartHTML();},
 print:()=>window.print(),
 excel:()=>{const f=state.filters.report||{};return api.download(f.mode==='movements'?'/reports/movements?'+query({...f,format:'xlsx'}):'/reports/excel?'+query(f),'Bao_cao_Vi_sinh.xlsx');},
 labels:async id=>{const r=await api.request('/imports/'+id+'/labels');state.labels=r.labels;modal(`<h2>Tem phiếu nhập</h2><div class="label-preview">${labelHTML(r.labels)}</div><div class="dialog-actions">${button('In tem','print-labels','','primary')}</div>`);},
 'print-labels':printLabels,
 'cancel-ticket':id=>modal(`<h2>Hủy phiếu & hoàn tồn</h2><p>Chỉ được hủy trong thời hạn do admin cấu hình. Lịch sử phiếu gốc và phiếu đảo được giữ lại.</p><form data-form="cancel" data-id="${id}"><br><label>Lý do bắt buộc<textarea name="cancel_reason" required maxlength="1000"></textarea></label><div class="dialog-actions"><button type="submit" class="danger">Xác nhận hủy và hoàn tồn</button></div></form>`),
 'adjust-stock':async id=>{await api.mutate('/stocktakes/'+id+'/adjust',{});closeModal();notice('Đã điều chỉnh tồn theo phiếu kiểm kê.');await show('stocktake');},
 'edit-user':userForm,'edit-item':itemForm,
 'delete-user':id=>modal(`<h2>Xóa tài khoản?</h2><p>Tài khoản không thể đăng nhập nữa. Dữ liệu lịch sử được giữ nguyên.</p><form data-form="delete-user" data-id="${id}"><div class="dialog-actions"><button class="danger" type="submit">Xác nhận xóa tài khoản</button></div></form>`),
 password:()=>modal(`<h2>Đổi mật khẩu</h2><form data-form="password"><div class="form-grid">${field('Mật khẩu hiện tại','old_password','','password','required autocomplete="current-password"')}${field('Mật khẩu mới','new_password','','password','required minlength="10" maxlength="72" autocomplete="new-password"')}${field('Nhập lại mật khẩu mới','confirm_password','','password','required autocomplete="new-password"')}</div><button class="primary" type="submit">Đổi mật khẩu</button></form>`),
 category:()=>modal(`<h2>Nhóm danh mục</h2><form data-form="category"><div class="form-grid">${field('Mã nhóm','code','','text','required maxlength="20"')}${field('Tên nhóm','name','','text','required maxlength="100"')}<label>Loại<select name="type"><option value="HOA_CHAT">Hóa chất / Thuốc</option><option value="VAT_TU">Vật tư</option><option value="DUNG_CU">Dụng cụ</option></select></label></div><button class="primary">Lưu nhóm</button></form>`),
 location:()=>modal(`<h2>Vị trí lưu kho</h2><form data-form="location"><div class="form-grid">${field('Mã vị trí','code','','text','required maxlength="30"')}${field('Tên vị trí','name','','text','required maxlength="100"')}${field('Nhiệt độ','temp_range')}${field('Mô tả','description')}</div><button class="primary">Lưu vị trí</button></form>`)
};
const forms={
 filters:async(d)=>{state.filters[state.view]={...d,mode:state.filters[state.view]?.mode};await show(state.view);},
 'audit-filter':async d=>{state.filters.audit={...state.filters.audit,...d};await show('audit');},
 'inventory-scan':d=>batchDetail(d.code),
 'export-scan':async d=>{const {batch:b}=await api.scanBarcode(d.code.trim());if(b.is_expired||b.batch_status==='LOCKED')throw Error('Lô đã hết hạn hoặc bị khóa.');if(Number(b.current_quantity)<=0)throw Error('Lô đã hết tồn.');if(state.cart.some(x=>x.batch_id===b.batch_id))throw Error('Lô đã có trong danh sách. Sửa số lượng ngay trên dòng.');state.cart.push({...b,quantity:1});$('#cart').innerHTML=cartHTML();$('#content input[name="code"]').value='';$('#content input[name="code"]').focus();},
 import:async(d,form)=>{const items=[...$('#import-rows').children].map(tr=>Object.fromEntries([...tr.querySelectorAll('input,select')].map(e=>[e.name,['item_id','quantity','unit_price','label_print_count'].includes(e.name)?Number(e.value):e.value]))).map(i=>({...i,location_id:Number(d.location_id)}));const r=await api.mutate('/imports',{supplier_name:d.supplier_name,notes:d.notes,items});form.reset();$('#import-rows').innerHTML=importRow({});state.labels=r.ticket.batches;$('#label-result').innerHTML=`<div class="panel"><h3>Đã ghi sổ ${esc(r.ticket.ticket_code)}</h3><div class="label-preview">${labelHTML(state.labels)}</div><br>${button('In tem mã vạch','print-labels','','primary')}</div>`;notice('Nhập kho thành công. In tem hoặc in lại từ Phiếu giao dịch.');},
 export:async d=>{if(!state.cart.length)throw Error('Danh sách xuất đang trống.');for(const x of state.cart)if(!Number.isFinite(x.quantity)||x.quantity<=0||x.quantity>Number(x.current_quantity))throw Error('Số lượng xuất phải lớn hơn 0 và không vượt tồn.');state.exportPayload={department_name:d.department_name,notes:d.notes,export_type:state.view==='transfer'?'DIEU_CHUYEN':'XUAT_KHOA',items:state.cart.map(x=>({batch_id:x.batch_id,quantity:x.quantity}))};modal(`<h2>Bước 2/2 · Xác nhận phiếu xuất</h2><p>Khoa / Đơn vị: <strong>${esc(d.department_name)}</strong></p><p>Lý do: ${esc(d.notes)}</p><div class="review-list">${table(['Lô','Mặt hàng','Số lượng'],state.cart.map(x=>`<tr>${td(x.batch_code)}${td(x.item_name)}${td(num(x.quantity)+' '+x.unit)}</tr>`))}</div><form data-form="confirm-export"><div class="dialog-actions"><button class="primary" type="submit">Xác nhận & Ghi sổ xuất</button></div></form>`);},
 'confirm-export':async()=>{const r=await api.mutate('/exports',state.exportPayload);state.cart=[];state.exportPayload=null;closeModal();notice(r.message);await show('transactions');},
 cancel:async(d,f)=>{const r=await api.mutate('/exports/'+f.dataset.id+'/cancel',d);closeModal();notice(r.message);await show('transactions');},
 'start-stocktake':async d=>{const r=await api.getInventory({location_id:d.location_id,include_zero:'true'});state.stockRows=r.inventory;state.stockLocation=Number(d.location_id);if(!r.inventory.length)throw Error('Không có lô tại vị trí này.');$('#content').innerHTML=`<form data-form="save-stocktake"><div class="panel"><h3>Ghi số đếm thực tế</h3><p class="muted">Nhập lý do khi có chênh lệch. Sau khi lưu cần đối soát và xác nhận điều chỉnh.</p>${table(['Lô','Mặt hàng','Số sổ','Thực đếm','Lý do chênh lệch'],r.inventory.map((x,i)=>`<tr>${td(x.batch_code)}${td(x.item_name)}${td(num(x.current_quantity))}<td><input name="actual-${i}" type="number" min="0" step="0.001" required value="${x.current_quantity}"></td><td><input name="reason-${i}" maxlength="255"></td></tr>`))}</div><div class="actionbar"><span>Bước 1 · Lưu bản kiểm kê</span><button class="primary">Lưu & Đối soát</button></div></form>`;},
 'save-stocktake':async d=>{const items=state.stockRows.map((x,i)=>({batch_id:x.batch_id,actual_quantity:Number(d['actual-'+i]),expected_quantity:Number(x.current_quantity),reason:d['reason-'+i]}));for(const i of items)if(i.actual_quantity!==i.expected_quantity&&!i.reason.trim())throw Error('Nhập lý do cho từng lô có chênh lệch.');const r=await api.mutate('/stocktakes',{location_id:state.stockLocation,items});await show('stocktake');await stockDetail(r.stocktake_id);},
 user:async(d,f)=>{d.can_import=d.can_import==='on';d.can_export=d.can_export==='on';await api.request('/users'+(f.dataset.id?'/'+f.dataset.id:''),{method:f.dataset.id?'PUT':'POST',body:JSON.stringify(d)});closeModal();notice('Đã lưu tài khoản.');await show('admin');},
 'delete-user':async(_,f)=>{await api.request('/users/'+f.dataset.id,{method:'DELETE'});closeModal();notice('Đã xóa tài khoản khỏi danh sách sử dụng.');await show('admin');},
 password:async d=>{if(d.new_password!==d.confirm_password)throw Error('Mật khẩu nhập lại chưa khớp.');await api.request('/auth/password',{method:'PUT',body:JSON.stringify(d)});logout();$('#login-error').textContent='Đã đổi mật khẩu. Vui lòng đăng nhập lại.';},
 item:async(d,f)=>{d.category_id=Number(d.category_id);d.min_stock=Number(d.min_stock);d.expire_alert_days=d.expire_alert_days?Number(d.expire_alert_days):null;await api.request('/items'+(f.dataset.id?'/'+f.dataset.id:''),{method:f.dataset.id?'PUT':'POST',body:JSON.stringify(d)});closeModal();notice('Đã lưu mặt hàng.');await show('items');},
 category:async d=>{await api.request('/categories',{method:'POST',body:JSON.stringify(d)});closeModal();notice('Đã thêm nhóm danh mục.');await show('items');},
 location:async d=>{await api.request('/locations',{method:'POST',body:JSON.stringify(d)});closeModal();notice('Đã thêm vị trí.');await show('locations');},
 config:async d=>{await api.request('/configs',{method:'PUT',body:JSON.stringify(d)});notice('Đã áp dụng cấu hình.');}
};
document.addEventListener('click',async e=>{const el=e.target.closest('[data-action]');if(!el)return;const fn=actions[el.dataset.action];if(!fn)return;el.disabled=true;try{await fn(el.dataset.id,el);}catch(err){error(err);if($('#modal').open){let box=$('#modal .modal-error');if(!box){box=document.createElement('p');box.className='error modal-error';$('#modal-content').append(box);}box.textContent=err.message;}}finally{el.disabled=false;}});
document.addEventListener('submit',async e=>{const f=e.target;if(!f.dataset.form)return;e.preventDefault();if(f.dataset.busy)return;f.dataset.busy='1';const submit=f.querySelector('[type="submit"],button:not([type])');if(submit)submit.disabled=true;try{await forms[f.dataset.form](Object.fromEntries(new FormData(f)),f);}catch(err){error(err);let p=f.querySelector('.form-error');if(!p){p=document.createElement('p');p.className='error form-error';f.append(p);}p.textContent=err.message;}finally{delete f.dataset.busy;if(submit)submit.disabled=false;}});
document.addEventListener('change',e=>{if(e.target.dataset.cart!=null)state.cart[Number(e.target.dataset.cart)].quantity=Number(e.target.value);if(e.target.id==='report-mode'){state.filters.report={...state.filters.report,mode:e.target.value};show('report');}});
document.addEventListener('keydown',e=>{if(!state.user||$('#modal').open)return;if(['F2','F3','F4','F9'].includes(e.key)){e.preventDefault();if(e.key==='F3'&&can('can_import'))show('import');if(['F2','F4'].includes(e.key)&&can('can_export'))show('export');if(e.key==='F9'&&state.view==='import')$('#content form').requestSubmit();}});
window.addEventListener('auth-expired',()=>logout());
document.addEventListener('DOMContentLoaded',()=>{
 $('#server-url').value=api.baseUrl;
 const switchAuth = register => { $('#login-form').hidden=register; $('#register-form').hidden=!register; $('#login-error').textContent=''; $('#register-error').textContent=''; $('#login-success').textContent=''; (register ? $('#register-form').elements.full_name : $('#login-form').elements.username).focus(); };
 $('#show-register').addEventListener('click',()=>switchAuth(true));
 $('#show-login').addEventListener('click',()=>switchAuth(false));
 $('#register-form').addEventListener('submit',async e=>{
  e.preventDefault();const f=e.target,b=f.querySelector('button[type="submit"]');b.disabled=true;$('#register-error').textContent='';
  try {
   const d=Object.fromEntries(new FormData(f));d.username=d.username.trim();d.full_name=d.full_name.trim();
   if(d.password!==d.confirm_password)throw Error('Mật khẩu nhập lại chưa khớp.');
   if(new TextEncoder().encode(d.password).length>72)throw Error('Mật khẩu tối đa 72 byte.');
   const url=$('#server-url').value.trim().replace(/\/$/,'');if(!/^https?:\/\//.test(url))throw Error('Địa chỉ máy chủ không hợp lệ. Vui lòng quay lại đăng nhập để chỉnh kết nối máy chủ.');
   api.baseUrl=url;localStorage.setItem('visinh_api_url',url);
   const r=await api.request('/auth/register',{method:'POST',body:JSON.stringify(d)});
   f.reset();switchAuth(false);$('#login-form').elements.username.value=d.username;$('#login-form').elements.password.value='';$('#login-success').textContent=r.message;
  } catch(err){$('#register-error').textContent=err.message;}finally{b.disabled=false;}
 });
 $('#login-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.target,b=f.querySelector('button[type="submit"]');b.disabled=true;$('#login-error').textContent='';try{const url=$('#server-url').value.trim().replace(/\/$/,'');if(!/^https?:\/\//.test(url))throw Error('Địa chỉ máy chủ không hợp lệ.');api.baseUrl=url;localStorage.setItem('visinh_api_url',url);const d=Object.fromEntries(new FormData(f)),r=await api.login(d.username,d.password);api.setToken(r.token);f.elements.password.value='';await session();}catch(err){$('#login-error').textContent=err.message;}finally{b.disabled=false;}});
 if(api.token)session().catch(err=>{logout();$('#login-error').textContent=err.message;});
});
